### PR TITLE
Fixed typing on AbstractMeganetElement

### PR DESCRIPTION
**Pull request by DavidBegert**
Made typing more restrictive

### CODE REVIEW

**Comment by lruthotto** [comment]
can you explain what the difference between `Number` and `Real` is? Is there anything to be gained in terms of efficiency by restricting to `Real`? I think this is a valid assumption here. 

Otherwise looks like a good change to me, if is passes the tests :)

**Review by jgranek — APPROVED** [review]

**Comment by jgranek** [comment]
@lruthotto We weren't sure if you guys needed complex numbers for the fourier stuff (ie: `ConvFFTKernel.jl`). If we can assume that everything is Real we can certainly restrict more - I would guess that increases efficiency for compiling. Glad you're paying close attention! 👍

**Comment by lruthotto** [comment]
Well, the data and weights can be assumed to be `Real` in the applications we have in mind for now. You're right that in `convFFT` there are some temp variables that are Complex numbers. Those should be treated separaetely when typing I guess. Even for those, we need an option to have different precisions. E.g., if the data is Float32, the temp results in convFFT should be Complex64 which is the same as Complex{Float32}. 

Did you look into the data type `AbstractFloat`? Not sure if it still exists but I think this is closest to what we need. 

Thanks for your help on this!

**Comment by DavidBegert** [comment]
@lruthotto We can always restrict more further down the road when we have a better idea what kind of 'AbstractMeganet' sub elements we will have :)

**Comment by lruthotto** [comment]
Sure. Fine with me. Was just wondering if there is a difference for the efficiency when we have `AbstractFloat` (more specific) vs. `Real`. I didn't look what types are contained in each one. But we can do this later on.

**Pull request merged**
